[build]
  command = "rm -f .babelrc && npm install && npm install onnxruntime-web@1.16.3 typescript@5.3.3 @types/react@19.0.0 @types/react-dom@19.0.0 @types/node@20.10.0 --no-save && npm run build"
  publish = ".next"
  environment = { NEXT_DISABLE_ESLINT = "1", NODE_ENV = "production", CI = "false" }

[[plugins]]
  package = "@netlify/plugin-nextjs" 