[build]
  command = "npm ci && npm run build"
  publish = ".next"
  environment = { NEXT_DISABLE_ESLINT = "1", NODE_ENV = "production", CI = "false" }

[[plugins]]
  package = "@netlify/plugin-nextjs" 